### ISSUE TITLE
Examples are broken :(

### ISSUE THREAD

**Issue by jimthedev** [Cmdv/rxjs-image-zoom#4]
Looks neat but clicking on Drag + Drop brings me to Image Zoom I think. All other links broken pages. :(

![screen shot 2015-06-29 at 12 10 34 pm](https://cloud.githubusercontent.com/assets/108938/8413690/e23a2afc-1e57-11e5-9a2b-945113e2ba00.png)

**Comment by jimthedev** [comment]
Looks like the image zoom example works if your screen is big. Drag + Drop doesn't seem to do anything right now and I can't get Drag + Drop 2 to trigger a page load.

**Comment by Cmdv** [comment]
@jimthedev yes the drag and drop hasn't been put up yet I will I will remove the inks so not to confuse people!!
I will look into the imagezoom example to work on smaller screens, it will be something to do with the div.

But thanks for letting me know :)

**Comment by Cmdv** [comment]
Now working on drag and drop but hoverzoom has been fixed, will close issue as other pages are no longer active

**Comment by jimthedev** [comment]
Thanks!
